# -*- coding: utf-8 -*-
"""cv-7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WLgqR2lGjo7ryI5M6vpvbp2NjwPi7hK
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def filtered_image(img, kernel, p, s):
  rows = (img.shape[0] - kernel.shape[0] + 2 * p) // s + 1
  cols = (img.shape[1] - kernel.shape[1] + 2 * p) // s + 1
  output = np.zeros((rows, cols), dtype=img.dtype)

  if p == 0:
    padded_img = img
  else:
    padded_img = np.pad(img, p, mode='constant', constant_values=0)

  for i in range(rows):
    for j in range(cols):
      # Extract the region of interest from the padded image
      # using stride 's' for movement
      roi = padded_img[i*s : i*s + kernel.shape[0], j*s : j*s + kernel.shape[1]]
      # Ensure ROI matches kernel shape for element-wise multiplication
      if roi.shape == kernel.shape:
        output[i][j] = np.sum(roi * kernel)
      else:
        # Handle cases where ROI might be smaller at edges if padding isn't perfect for stride
        # For now, setting to 0 or handling as per specific requirement.
        # A more robust solution might involve careful padding or different edge handling.
        output[i][j] = 0
  return output

k = 15
img_path ="/content/CAT2.jpg"

img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE) # Read as grayscale for simplicity

# Check if image was loaded successfully. If not, use the dummy image.
if img is None:
    print(f"Warning: Could not load image from {img_path}. Creating a dummy 100x100 black image instead.")
    # Create a dummy 100x100 black image if loading fails
    img = np.zeros((100, 100), dtype=np.uint8)


kernel = np.ones((k, k)) / (k**2)
filtered_img = filtered_image(img, kernel, p=1, s=2)

plt.imshow(filtered_img, cmap='gray')
plt.title('Filtered Image')
plt.axis('off')
plt.show()

rows, cols = filtered_img.shape
angle_img = np.zeros((rows, cols), dtype=float) # Placeholder for angle image

for i in range(rows):
  for j in range(cols):
    angle_value=angle_img[i][j]
    if -225<= angle_value<=225:
      angle_img[i][j]=0
    elif 22.5<=angle_value<=67.5:
      angle_img[i][j]=45
    elif 67.5<=angle_value<=112.5:
      angle_img[i][j]=90

for i in range(1,quantired_angles shape[0]):
  for j in range(1,quantired_angles shape[1]):
     angles_value=quantired_angles[i-1][j-1]